## Creating Arrays

In [3]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
c = np.array([[(1.5, 2, 3), (4,5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)
print(a)
print(b)
print(c)

## Initial Placeholders ##

In [10]:
zero_arr = np.zeros((3,4), dtype=int) # Create an array of zeros
ones_arr = np.ones((2,3,4), dtype=np.int16) # Create an array of ones
d = np.arange(10, 25, 5) # Create an array of evenly spaced values (step value)
linspace_arr = np.linspace(0, 2, 9) # Create an array of evenly spaced values (number of samples)
e = np.full((2,2), 7) # Create a constant array
f = np.eye(2) # Create a 2X2 identity matrix
rand_arr = np.random.random((2,2)) # Create an array with random values
empty_arr = np.empty((3,2)) # Create an empty array

print(f'Zero array -> {zero_arr}')
print(f'Ones array -> {ones_arr}')
print(f'Arange -> {d}')
print(f'linspace -> {linspace_arr}')
print(f'constant array -> {e}')
print(f'identity matrix -> {f}')
print(f'random array -> {rand_arr}')
print(f'empty array -> {empty_arr}')

Zero array -> [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ones array -> [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Arange -> [10 15 20]
linspace -> [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
constant array -> [[7 7]
 [7 7]]
identity matrix -> [[1. 0.]
 [0. 1.]]
random array -> [[0.36018357 0.36445596]
 [0.07468488 0.47190356]]
empty array -> [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


## Saving and Loading on Disk ##

In [11]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

## Saving and loading text files ##

In [16]:
np.loadtxt("myfile.txt")
np.genfromtxt("myfile.csv", delimiter=",")
np.savetxt("my_array.txt", a, delimiter=" ")

## Asking for help ##

In [17]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
