<a name='1'></a>
# 1 - Basics of NumPy #

NumPy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. This notebook is a playground to learn NumPy functions that will help in future assignments, such as creating arrays, slicing, indexing, reshaping and stacking.

<a name='1-1'></a>
## 1.1 - Packages ##
Before getting started, we have to import NumPy to load its functions as below. 

In [2]:
import numpy as np

<a name='1-2'></a>
## 1.2 - Advantages of using NumPy arrays ##
Arrays are one of the core data structures of the NumPy library, essential for organizing your data. You can think of them as a grid of values, all of the same type. Arrays are analogous to the matrices you saw in the video lessons. If you have used Python lists before, you may remember that they are convenient, as you can store different data types. However, Python lists are limited in functions and take up more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only a few lines of code. This can be a huge advantage when performing math operations on large datasets. 

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.

In [3]:
one_dimensional_array = np.array([10, 12])
print(one_dimensional_array)

[10 12]


<a name='1-3'></a>
## 1.3 - How to create NumPy arrays ##

There are several ways to create an array in NumPy. You can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array.

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval. To learn more about the arguments that this function takes, there is a powerful feature in Jupyter Notebook that allows you to access the documentation of any function by simply pressing `shift+tab` on your keyboard when clicking on the function. Give it a try for the built-in documentation of `np.arange()`. 

In [5]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [6]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in  this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using `np.linspace()`.

In [7]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


Did you notice that the output of the function is presented in the float value form (e.g. "... 25. 50. ...")? The reason is that the default type for values in the NumPy function `np.linspace` is a floating point (`np.float64`). You can easily specify your data type using `dtype`. If you access the built-in documentation of the functions, you may notice that most functions take in an optional parameter `dtype`. In addition to float, NumPy has several other data types such as `int`, and `char`. 

To change the type to integers, you need to set the dtype to `int`. You can do so, even in the previous functions. Feel free to try it out and modify the cells to output your desired data type. 

In [8]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [9]:
c_int = np.arange(0, 25, 4, dtype=int)
print(c_int)

[ 0  4  8 12 16 20 24]


In [10]:
c_float = np.arange(0, 30, 2, dtype=float)
print(c_float)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


In [11]:
char_arr = np.array(['Welcome to Machine Learning'])
print(char_arr)

['Welcome to Machine Learning']


In [12]:
print(len(char_arr))

1


In [13]:
print(char_arr.dtype)

<U27


Did you notice that the output of the data type of the `char_arr` array is `<U27`? 
This means that the string (`'Welcome to Math for ML!'`) is a 27-character (27) unicode string (`U`) on a little-endian architecture (`<`). You can learn more about data types [here](https://numpy.org/doc/stable/user/basics.types.html).

<a name='1-4'></a>
## 1.4 - More on NumPy arrays ##

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as: 
- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero.
- `np.empty()` - Returns a new uninitialized array. 
- `np.random.rand()` - Returns a new array with values chosen at random.

In [14]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [15]:
ones_arr = np.ones(3, dtype=int)
print(ones_arr)

[1 1 1]


In [16]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [17]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [18]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.10700456 0.464844   0.82684783]


<a name='2'></a>
# 2 - Multidimensional Arrays #
With NumPy we can also create arrays with more than one dimension. In the above examples, we dealt with 1-D arrays, where we can access their elements using a single index. A multidimensional array has more than one column. 

In [19]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `np.reshape()` we can rearrange elements of the previous array into a new shape. 

In [20]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])
multi_dim_arr = np.reshape(one_dim_arr, (2, 3))

In [22]:
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


<a name='2-1'></a>
## 2.1 - Finding size, shape and dimension. ##

Following are all atrributes of a `ndarray` and can be accessed as follows:
- `ndarray.ndim` - Stores the number dimensions of the array. 
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- `ndarray.size` - Stores the number of elements in the array.

- `ndarray` - n dimensional array

In [23]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [25]:
# Shape of the multi dimensional array (shape describes the number of rows and columns for the multi dimensional array)
multi_dim_arr.shape

(2, 3)

In [26]:
# size of the array
multi_dim_arr.size

6

<a name='3'></a>
# 3 - Array math operations #
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list. Meanwhile, trying to subtract or multipy Python lists simply would cause an error.

In [27]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
sum_arr = arr_1 + arr_2
print(sum_arr)

[5 7 9]


In [28]:
diff_arr = arr_1 - arr_2
print(diff_arr)

[-3 -3 -3]


In [30]:
mul_arr = arr_1 * arr_2
print(mul_arr)

[ 4 10 18]


<a name='3-1'></a>
## 3.1 - Multiplying vector with a scalar (broadcasting) ##
Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplication within each cell. 

This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes.

In [32]:
vector = np.array([1, 2.5, 3])
vector * 1.6

array([1.6, 4. , 4.8])

<a name='4'></a>
# 4 - Indexing and slicing #
Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays. 

## 4.1 - Indexing ##
Let us select specific elements from the arrays as given. 

In [34]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension. There are two common ways to do this, either by using two sets of brackets, or by using a single bracket and separating each index by a comma. Both methods are shown here.

In [35]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j and two sets of brackets
print(two_dim[2][1])

# Select element number 8 from the 2-D array, this time using i and j indexes in a single 
# set of brackets, separated by a comma
print(two_dim[2,1])

8
8


<a name='4-2'></a>
## 4.2 - Slicing ##
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive). 

The syntax is:

`array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed to end, it is assumed that `end = length of array - 1` and if no value is passed to step, it is assumed `step = 1`.

Note you can use slice notation with multi-dimensional indexing, as in `a[0:2, :5]`. This is the extent of indexing you'll need for this course but feel free to check out [the official NumPy documentation](https://numpy.org/doc/stable/user/basics.indexing.html) for extensive documentation on more advanced NumPy array indexing techniques.

In [36]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [37]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[0:3]
print(sliced_arr)

[1 2 3]


In [40]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:5]
print(sliced_arr)

[3 4 5]


In [42]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


In [43]:
# Note that a == a[:] == a[::]
print(f'a == a[:]: {a == a[:]}')
print(f'a[:] == a[::]: {a[:] == a[::]}')

a == a[:]: [ True  True  True  True  True]
a[:] == a[::]: [ True  True  True  True  True]


In [47]:
# Slice the two_dim array to get the first two rows
sliced_arr = two_dim[:2]
print(sliced_arr)

[[1 2 3]
 [4 5 6]]


In [49]:
# Similarily, slice the two_dim array to get the last two rows
sliced_arr = two_dim[1:]
print(sliced_arr)

[[4 5 6]
 [7 8 9]]


In [50]:
# This example uses slice notation to get every row, and then pulls the second column.
# Notice how this example combines slice notation with the use of multiple indexes
sliced_arr = two_dim[:, 1]
print(sliced_arr)

[2 5 8]
